openwebui-setup: small fixes

diff --git a/ollama-docker/openwebui-setup b/ollama-docker/openwebui-setup
--- a/ollama-docker/openwebui-setup
+++ b/ollama-docker/openwebui-setup
@@ -1,6 +1,8 @@
 #!/bin/bash
 
-WEBUI_CONFIG="$HOME/.config/webui-path.conf"
+WEBUI_CONFIG="$HOME/.config/openwebui-path.conf"
+
+ERROR=false
 
 _echo() { echo -e "\e[1m==> $@\e[0m"; }
 
@@ -11,17 +13,24 @@ fi
 
 
 if test -f "$WEBUI_CONFIG"; then
-    STORAGE_LOC="$(cat $WEBUI_CONFIG)"
     _echo "Loading config..."
-    echo "Storage location: $STORAGE_LOC"
+    STORAGE_LOC="$(cat $WEBUI_CONFIG)"
+
+    if test -z "$STORAGE_LOC"; then
+        echo -e "\e[1;31mERROR\e[0m: config file is empty!\n"
+        ERROR=true
+    else
+        echo "Using storage: $STORAGE_LOC"
+    fi
 else
     STORAGE_LOC="$1"
+fi
 
-    if test -z "$1"; then
-        echo -e "\e[31;1mERROR\e[0m: please, specify a directory for Open WebUI data\n"
-        echo -e "\e[1mUsage\e[0m:\n  $0 <directory>"
-        exit 1
-    fi
+
+if $ERROR || test -z "$STORAGE_LOC"; then
+    echo -e "Please, specify a directory for Open WebUI data\n"
+    echo -e "\e[1mUsage\e[0m:\n  $0 <directory>"
+    exit 1
 fi
 
 
@@ -32,9 +41,11 @@ fi
 
 
 if ! test -f "$WEBUI_CONFIG"; then
-    echo -e "\e[1mNOTE\e[0m: the path will be remembered. To reset, remove the following file:"
-    echo -e "    ${WEBUI_CONFIG/$HOME/\~}\n"
     echo "$STORAGE_LOC" > $WEBUI_CONFIG
+    echo -e "\e[1mNOTE\e[0m: the path will be remembered for easy upgrade."
+    echo -e "    ${WEBUI_CONFIG/$HOME/\~}\n"
+    echo    "To change the path, just call this script with the new path."
+    echo    "This script won't move your Open-WebUI data to the new location."
 fi
 
 _echo "Pulling ghcr.io/open-webui/open-webui ...\e[0m"
